class PokemonTypeColors {
  static const colours = {
    PokemonTypeNames.normal: '0xffA8A77A',
    PokemonTypeNames.fire: '0xffEE8130',
    PokemonTypeNames.water: '0xff6390F0',
    PokemonTypeNames.electric: '0xffF7D02C',
    PokemonTypeNames.grass: '0xff7AC74C',
    PokemonTypeNames.ice: '0xff96D9D6',
    PokemonTypeNames.fighting: '0xffC22E28',
    PokemonTypeNames.poison: '0xffA33EA1',
    PokemonTypeNames.ground: '0xffE2BF65',
    PokemonTypeNames.flying: '0xffA98FF3',
    PokemonTypeNames.psychic: '0xffF95587',
    PokemonTypeNames.bug: '0xffA6B91A',
    PokemonTypeNames.rock: '0xffB6A136',
    PokemonTypeNames.ghost: '0xff735797',
    PokemonTypeNames.dragon: '0xff6F35FC',
    PokemonTypeNames.dark: '0xff705746',
    PokemonTypeNames.steel: '0xffB7B7CE',
    PokemonTypeNames.fairy: '0xffD685AD',
  };
}

enum PokemonTypeNames {
  normal,
  fire,
  water,
  electric,
  grass,
  fifthStep,
  ice,
  fighting,
  poison,
  ground,
  flying,
  psychic,
  bug,
  rock,
  ghost,
  dragon,
  dark,
  steel,
  fairy,
}
